on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test and report
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000

      - name: Fetch base
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000

      - name: Run tests
        run: |
          npm i
          npm run test

      - name: Report coverage
        id: hello
        uses: ./
        with:
          coverage_output_directory: 'coverage'
