name: Pull request actions
on:
  issue_comment:                                     
    types: [created]

jobs:
  on_comment:
    if: contains(github.event.comment.body, '/merge')
    name: On merge comment
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000

      - name: Fetch base
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000

      - name: Execute PR actions
        run: node .github/workflows/pr-actions.js